<?php
require __DIR__.'/sqlite-bootstrap.php';
spl_autoload_register(function($c){$prefix='EducacionalERP\\';if(str_starts_with($c,$prefix))require dirname(__DIR__).'/src/'.str_replace('\\','/',substr($c,strlen($prefix))).'.php';});
function sanitize_textarea_field($s){return strip_tags($s);}
function sanitize_file_name($s){return basename($s);}
function checkChat($v,$m){if(!$v)throw new RuntimeException($m);echo "PASS: $m\n";}
function deniedChat($fn,$m){try{$fn();}catch(EducacionalERP\Domain\RuleViolation $e){checkChat(true,$m);return;}throw new RuntimeException('Falha: '.$m);}
function ck(){return bin2hex(random_bytes(20));}
use EducacionalERP\Infrastructure\Database\Database;
use EducacionalERP\Infrastructure\WordPress\Access;
use EducacionalERP\Application\ChatService;
$db=new Database($wpdb);Access::install();wp_set_current_user(1);
$person=$db->insert('pessoas',['nome'=>'MAE','data_nascimento'=>'1980-01-01']);$child=$db->insert('pessoas',['nome'=>'ALUNO','data_nascimento'=>'2015-01-01']);$student=$db->insert('alunos',['codpessoa'=>$child,'ra'=>'001']);$user=wp_insert_user(['user_login'=>'mae','display_name'=>'Mãe','role'=>'erp_responsavel']);$db->insert('pessoa_usuarios',['codpessoa'=>$person,'wp_user_id'=>$user]);$db->insert('aluno_responsaveis',['idaluno'=>$student,'codpessoa_responsavel'=>$person,'parentesco'=>'mae','responsavel_academico'=>1,'inicio_vigencia'=>'2020-01-01 00:00:00']);
$staff=wp_insert_user(['user_login'=>'secretaria','display_name'=>'Secretaria','role'=>'erp_secretaria']);$other=wp_insert_user(['user_login'=>'outra.secretaria','display_name'=>'Outra secretaria','role'=>'erp_secretaria']);$supervisor=wp_insert_user(['user_login'=>'supervisao','display_name'=>'Supervisor','role'=>'erp_supervisao']);$stranger=wp_insert_user(['user_login'=>'outra.mae','display_name'=>'Outra mãe','role'=>'erp_responsavel']);
$chat=new ChatService($db);$channel=$chat->saveChannel(['nome'=>'Secretaria','ativo'=>true,'membros'=>[$staff]],ck())['idcanal'];$second=$db->insert('coligadas',['nome'=>'OUTRA','razao_social'=>'OUTRA']);$channel2=$chat->saveChannel(['nome'=>'Canal outra escola','codcoligada'=>$second,'ativo'=>true,'membros'=>[]],ck())['idcanal'];
wp_set_current_user($user);checkChat(count($chat->channels()['items'])===1,'família só vê canais das coligadas vinculadas');deniedChat(fn()=>$chat->start(['idcanal'=>$channel,'codpessoa'=>$child],ck()),'responsável não inicia conversa de outra pessoa');deniedChat(fn()=>$chat->start(['idcanal'=>$channel2],ck()),'responsável não acessa canal de outra coligada');deniedChat(fn()=>$chat->saveChannel(['nome'=>'Errado'],ck()),'responsável não administra canais');
$k=ck();$conv=$chat->start(['idcanal'=>$channel],$k)['idconversa'];checkChat($chat->start(['idcanal'=>$channel],$k)['idconversa']===$conv,'conversa idempotente');$k=ck();$message=$chat->send($conv,['texto'=>'Olá'], $k);checkChat($chat->send($conv,['texto'=>'Olá'],$k)===$message,'envio idempotente não duplica mensagem');
wp_set_current_user($stranger);deniedChat(fn()=>$chat->messages($conv),'outra família não lê histórico');deniedChat(fn()=>$chat->send($conv,['texto'=>'Errado'],ck()),'outra família não envia');
wp_set_current_user($other);deniedChat(fn()=>$chat->messages($conv),'secretaria fora do canal não lê conversa');checkChat(count($chat->conversations()['items'])===0,'listagem não vaza conversa a atendente fora do canal');
wp_set_current_user($staff);checkChat(count($chat->messages($conv)['items'])===1,'atendente do canal lê histórico');$chat->send($conv,['texto'=>'Boa tarde'],ck());checkChat(count($chat->recipients($channel,'',1)['items'])===1,'atendente pode buscar responsável antes de ser acionado');checkChat(count($chat->conversations()['items'])===1,'atendente recebe conversa do canal');
$secondFamily=$db->insert('pessoas',['nome'=>'OUTRA FAMILIA','data_nascimento'=>'1980-01-01']);$secondUser=wp_insert_user(['user_login'=>'segunda.familia','display_name'=>'Outra família','role'=>'erp_responsavel']);$db->insert('pessoa_usuarios',['codpessoa'=>$secondFamily,'wp_user_id'=>$secondUser]);$db->insert('aluno_responsaveis',['idaluno'=>$student,'codpessoa_responsavel'=>$secondFamily,'parentesco'=>'pai','responsavel_academico'=>1,'inicio_vigencia'=>'2020-01-01 00:00:00']);$initiated=$chat->start(['idcanal'=>$channel,'codpessoa'=>$secondFamily],ck())['idconversa'];$chat->send($initiated,['texto'=>'Contato iniciado pela escola'],ck());checkChat(count($chat->messages($initiated)['items'])===1,'escola inicia mensagem sem contato anterior da família');
wp_set_current_user($supervisor);checkChat(count($chat->conversations()['items'])===2&&count($chat->channels()['items'])===2,'supervisão vê todos os canais e históricos');
wp_set_current_user($user);$chat->read($conv,999);checkChat((int)$chat->conversations()['items'][0]['nao_lidas']===0,'leitura atualiza contador');
deniedChat(fn()=>$chat->send($conv,['anexos'=>[['nome'=>'arquivo.php','conteudo'=>base64_encode('<?php echo 1;')]]],ck()),'anexo executável bloqueado');
if(class_exists('finfo')){$chat->send($conv,['anexos'=>[['nome'=>'orientacao.txt','conteudo'=>base64_encode('Orientacao para a familia')]]],ck());$last=$chat->messages($conv)['items'];$last=end($last);$fileId=(int)$last['anexos'][0]['idanexo'];checkChat(base64_decode($chat->attachment($fileId)['conteudo'])==='Orientacao para a familia','anexo privado preservado');wp_set_current_user($stranger);deniedChat(fn()=>$chat->attachment($fileId),'download bloqueado a outra familia');wp_set_current_user($user);}
wp_set_current_user(1);$row=$db->get('chat_canais',$channel);$chat->saveChannel(['idcanal'=>$channel,'versao'=>$row['versao'],'nome'=>'Secretaria','ativo'=>false,'membros'=>[$staff]],ck());wp_set_current_user($user);checkChat(count($chat->messages($conv)['items'])>=2,'desativação mantém histórico');deniedChat(fn()=>$chat->send($conv,['texto'=>'Teste'],ck()),'canal desativado não recebe mensagens');
echo "PASS: chat com autorização por canal/família, supervisão, idempotência e histórico\n";
