<?php
require __DIR__.'/payment-plans.php';
use EducacionalERP\Application\{ContractDiscounts,FinanceService};
use EducacionalERP\Domain\{Input,FinancialStatus};
wp_set_current_user(1);$discounts=new ContractDiscounts($db,$ops);$finance=new FinanceService($db,$ops);$titles=$db->rows('SELECT l.* FROM '.$db->table('lancamentos').' l JOIN '.$db->table('parcelas').' p ON p.idparcela=l.idparcela WHERE p.idcontrato=%d ORDER BY p.numero',[$ct]);$today=Input::today();$futureDate=(new DateTimeImmutable($today))->modify('+30 days')->format('Y-m-d');foreach($titles as $title)$db->update('lancamentos',(int)$title['idlancamento'],['vencimento'=>$futureDate]);
$d1=$discounts->add($ct,['nome'=>'Bolsa','valor'=>'50.00','parcela_inicio'=>1,'parcela_fim'=>3],keyP());$d2=$discounts->add($ct,['nome'=>'Indicacao','valor'=>'20.00','parcela_inicio'=>2,'parcela_fim'=>3],keyP());$first=(int)$titles[0]['idlancamento'];$second=(int)$titles[1]['idlancamento'];$third=(int)$titles[2]['idlancamento'];testP($db->get('lancamentos',$first)['desconto_incondicional']==='50.00'&&$db->get('lancamentos',$second)['desconto_incondicional']==='70.00','bolsas somadas somente na faixa cadastrada');$before=$db->get('lancamentos',$second);deniedP(fn()=>$discounts->add($ct,['nome'=>'Excessivo','valor'=>'999.00','parcela_inicio'=>1,'parcela_fim'=>3],keyP()),'soma acima do original bloqueada');testP($db->get('lancamentos',$second)===$before,'falha reverte desconto e parcelas');
$discounts->saveSettings(['valor'=>'30.00'],keyP());$present=FinancialStatus::present($db->get('lancamentos',$first));testP($present['desconto_condicional']==='30.00'&&$present['valor_liquido']==='253.34','valor líquido público considera bolsa e pontualidade');$key=keyP();$payment=$finance->pay($first,['valor_pago'=>'253.34','forma_pagamento'=>'pix','data_pagamento'=>$today],$key);$settled=$db->get('lancamentos',$first);testP($settled['saldo_aberto']==='0.00'&&$settled['valor_baixa']==='253.34'&&$settled['desconto_condicional_aplicado']==='30.00','baixa registra somente dinheiro e concede pontualidade');testP($db->get('baixas',(int)$payment['idbaixa'])['desconto_condicional_concedido']==='30.00','baixa guarda desconto concedido para estorno');$finance->reverse((int)$payment['idbaixa'],['motivo'=>'Teste'],keyP());testP($db->get('lancamentos',$first)['saldo_aberto']==='283.34'&&$db->get('lancamentos',$first)['desconto_condicional_aplicado']==='0.00','estorno restaura desconto e saldo');
$finance->pay($first,['valor_pago'=>'253.34','forma_pagamento'=>'pix'],keyP());$paidBefore=$db->get('lancamentos',$first);$finance->pay($second,['valor_pago'=>'10.00','forma_pagamento'=>'pix'],keyP());testP(EducacionalERP\Domain\Money::cents($db->get('lancamentos',$second)['desconto_condicional_aplicado'])===0,'pagamento parcial não concede desconto antecipado');$partialBefore=$db->get('lancamentos',$second);$d=$db->get('contrato_descontos',(int)$d2['iddesconto']);$discounts->remove((int)$d2['iddesconto'],['versao'=>$d['versao']],keyP());testP($db->get('lancamentos',$third)['desconto_incondicional']==='50.00','exclusão remove só um desconto de parcela futura');testP($db->get('lancamentos',$first)===$paidBefore&&$db->get('lancamentos',$second)===$partialBefore,'exclusão preserva baixa integral e parcial');
$yesterday=(new DateTimeImmutable($today))->modify('-1 day')->format('Y-m-d');$db->update('lancamentos',$third,['vencimento'=>$yesterday]);$old=$db->get('lancamentos',$third);$d=$db->get('contrato_descontos',(int)$d1['iddesconto']);$discounts->remove((int)$d1['iddesconto'],['versao'=>$d['versao']],keyP());testP($db->get('lancamentos',$third)===$old,'exclusão não altera parcela vencida');testP(FinancialStatus::present($old)['desconto_condicional']==='0.00','vencimento passado perde benefício de pontualidade');
// A late payment settles the full net without punctuality.
$finance->pay($third,['valor_pago'=>$old['saldo_aberto'],'forma_pagamento'=>'pix'],keyP());testP(EducacionalERP\Domain\Money::cents($db->get('lancamentos',$third)['desconto_condicional_aplicado'])===0,'pagamento atrasado não recebe pontualidade');
wp_set_current_user($rfUser);deniedP(fn()=>$discounts->add($ct,['nome'=>'Teste','valor'=>'1.00','parcela_inicio'=>1,'parcela_fim'=>1],keyP()),'responsável não concede bolsas');echo "PASS: bolsas, descontos e pontualidade concluídos\n";

wp_set_current_user(1);$pendingStudent=$flow->createStudent(['nome'=>'Aluno Bolsa Pendente','data_nascimento'=>'2012-01-01','ra'=>'BOLSA-PEND'],keyP());$cat->link((int)$pendingStudent['idaluno'],['codpessoa_responsavel'=>$rf,'parentesco'=>'mae','responsavel_financeiro'=>1],keyP());$pendingCase=$db->atomic(function()use($db,$academic,$pendingStudent,$next,$future){$enrolled=$academic->placeInside((int)$pendingStudent['idaluno'],$next,$future,keyP());return $enrolled+$academic->createContractInside((int)$enrolled['idmatricula'],['quantidade_parcelas'=>5,'primeiro_vencimento'=>'2027-01-01'],keyP(),true);});$pendingContract=(int)$pendingCase['idcontrato'];$saved=$discounts->add($pendingContract,['nome'=>'Bolsa futura','valor'=>'20.00','parcela_inicio'=>2,'parcela_fim'=>4],keyP());testP(parcelsP($pendingContract)===[],'bolsa cadastrada em contrato sem parcelas não antecipa geração');$academic->generateInstallments($pendingContract,keyP());$futureTitles=$db->rows('SELECT l.* FROM '.$db->table('lancamentos').' l JOIN '.$db->table('parcelas').' p ON p.idparcela=l.idparcela WHERE p.idcontrato=%d ORDER BY p.numero',[$pendingContract]);testP(EducacionalERP\Domain\Money::cents($futureTitles[0]['desconto_incondicional'])===0&&$futureTitles[1]['desconto_incondicional']==='20.00'&&$futureTitles[3]['desconto_incondicional']==='20.00'&&EducacionalERP\Domain\Money::cents($futureTitles[4]['desconto_incondicional'])===0,'geração posterior aplica faixa da bolsa');
