<?php
require __DIR__.'/import-links-enrollments.php';
use EducacionalERP\Application\Curriculum;
$c=new Curriculum($db);$type=(new EducacionalERP\Application\PreviousHistory($db))->typeSave(['nome'=>'Base comum'],k());$disc=$c->save('disciplinas',['codigo'=>'MAT','nome'=>'Matemática','idtipo_disciplina'=>$type['idtipo_disciplina']],k());$grade=$c->save('grades_curriculares',['codigo'=>'G1','nome'=>'Grade Regular','idcurso'=>$course],k());$g2=$c->save('grades_curriculares',['codigo'=>'G2','nome'=>'Grade alternativa','idcurso'=>$course],k());$item=$c->save('grade_disciplinas',['idgrade'=>$grade['idgrade'],'iddisciplina'=>$disc['iddisciplina'],'carga_horaria'=>'100.00'],k());$tg=$c->save('turma_grades',['idturma'=>$class,'idgrade'=>$grade['idgrade']],k());
$teacher=$c->save('professores',['codpessoa'=>$p2['id']],k());$td=$c->save('professor_disciplinas',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period],k());$assigned=$c->save('professor_turmas',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'idturma'=>$class,'codperiodo'=>$period],k());$hour=$c->save('professor_valores_hora',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period,'valor_hora'=>'50.00'],k());ok((float)$hour['valor_hora']===50.0,'hour value stored per teacher, discipline and period');
$teacher2=$c->save('professores',['codpessoa'=>$r['id']],k());$c->save('professor_disciplinas',['idprofessor'=>$teacher2['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period],k());$c->save('professor_turmas',['idprofessor'=>$teacher2['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'idturma'=>$class,'codperiodo'=>$period],k());ok(count($c->listing()['professor_turmas'])===2,'multiple teachers can share class discipline');
no(fn()=>$c->save('turma_grades',array_merge($tg,['idgrade'=>$g2['idgrade']]),k()),'new grade cannot remove assigned discipline');no(fn()=>$c->remove('grade_disciplinas',(int)$item['iditem'],['versao'=>$item['versao']],k()),'cannot remove discipline with assigned teachers');no(fn()=>$c->remove('professor_disciplinas',(int)$td['idvinculo'],['versao'=>$td['versao']],k()),'cannot remove qualification with assignments/rates');
$period2=$cat->create('periodos_letivos',['codigo'=>'2027','descricao'=>'Próximo','data_inicio'=>'2027-01-01','data_fim'=>'2027-12-31'],k())['id'];$c->save('professor_disciplinas',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period2],k());$h2=$c->save('professor_valores_hora',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period2,'valor_hora'=>'60.00'],k());ok((float)$db->get('professor_valores_hora',(int)$hour['idvalor'])['valor_hora']===50.0,'new period rate preserves original');no(fn()=>$c->save('professor_turmas',['idprofessor'=>$teacher['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'idturma'=>$class,'codperiodo'=>$period2],k()),'class period mismatch blocked');
$u=$db->row('SELECT wp_user_id FROM '.$db->table('pessoa_usuarios').' WHERE codpessoa=%d',[(int)$p2['id']]);ok(in_array('erp_professor',get_userdata((int)$u['wp_user_id'])->roles,true),'teacher role assigned to existing WP user');wp_set_current_user((int)$u['wp_user_id']);no(fn()=>$c->save('disciplinas',['codigo'=>'BAD'],k()),'teacher cannot change academic registrations');wp_set_current_user(1);$class2=$cat->create('turmas',['codperiodo'=>$period,'idcurso'=>$course,'idturno'=>$shift,'codigo'=>'1B','nome'=>'Outra turma','capacidade'=>10],k())['id'];$c->save('turma_grades',['idturma'=>$class2,'idgrade'=>$g2['idgrade']],k());ok(count($c->listing()['turma_grades'])===2,'same course and period supports distinct class grades');$course2=$cat->create('cursos',['codigo'=>'EF2','nome'=>'Outro curso'],k())['id'];$other=$c->save('grades_curriculares',['codigo'=>'OUTRA','nome'=>'Outro curso','idcurso'=>$course2],k());no(fn()=>$c->save('turma_grades',array_merge($tg,['idgrade'=>$other['idgrade']]),k()),'cross-course class grade blocked');
no(fn()=>$c->save('professor_valores_hora',['idprofessor'=>$teacher2['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period2,'valor_hora'=>'80'],k()),'qualification in another period cannot authorize rate');
$free=$c->save('professor_disciplinas',['idprofessor'=>$teacher2['idprofessor'],'iddisciplina'=>$disc['iddisciplina'],'codperiodo'=>$period2],k());$c->remove('professor_disciplinas',(int)$free['idvinculo'],['versao'=>$free['versao']],k());ok((bool)$db->get('professor_disciplinas',(int)$td['idvinculo']),'removing unused qualification in another period preserves original period');
echo "CURRICULUM_OK\n";
