<?php
require __DIR__.'/additional-fields.php';
use EducacionalERP\Application\ExternalPeopleApi;
function wp_salt($scheme){return 'test-api-salt';}function wp_http_validate_url($url){return str_starts_with($url,'https://crm.example.test/')?$url:false;}function add_query_arg($k,$v,$url){return $url.(str_contains($url,'?')?'&':'?').urlencode($k).'='.urlencode((string)$v);}function wp_safe_remote_get($url,$args){$GLOBALS['request_args']=$args;return ['code'=>$GLOBALS['http_code']??200,'body'=>json_encode($GLOBALS['response'])];}function wp_remote_retrieve_response_code($r){return $r['code'];}function wp_remote_retrieve_body($r){return $r['body'];}
$x=new ExternalPeopleApi($db,$cat);$GLOBALS['response']=['data'=>[['entry_id'=>'123','student'=>['name'=>'Aluno API','dob'=>'10/05/2010','sex'=>'M','cpf'=>'52998224725'],'father'=>['name'=>'Pai API','dob'=>'01/01/1980']]],'meta'=>['total'=>1,'page'=>1,'total_pages'=>1]];
$maps=[['pessoa'=>'aluno','origem'=>'student.cpf','destino'=>'cpf'],['pessoa'=>'aluno','origem'=>'','destino'=>'pais','padrao'=>'BR'],['pessoa'=>'aluno','origem'=>'student.name','destino'=>'nome'],['pessoa'=>'aluno','origem'=>'student.dob','destino'=>'data_nascimento'],['pessoa'=>'aluno','origem'=>'student.sex','destino'=>'sexo'],['pessoa'=>'pai','origem'=>'father.name','destino'=>'nome'],['pessoa'=>'pai','origem'=>'father.dob','destino'=>'data_nascimento']];
$config=$x->save(['url'=>'https://crm.example.test/api?per_page=50','usuario'=>'api','senha'=>'secret-api','caminho_lista'=>'data','campo_id'=>'entry_id','mapeamento'=>$maps],kk());check(!isset($config['senha'])&&$config['senha_configurada'],'credentials absent from public config');check(!str_contains(get_option('ederp_external_people_api')['senha'],'secret-api'),'password encrypted at rest');
$sample=$x->test();check(in_array('student.name',$sample['campos_origem'],true)&&$sample['quantidade']===1,'nested source fields discovered');check($GLOBALS['request_args']['redirection']===0&&$GLOBALS['request_args']['headers']['Authorization']==='Basic '.base64_encode('api:secret-api'),'Basic auth server-side without redirects');
$m=$x->map($GLOBALS['response']['data'][0]);check($m['aluno']['pais']==='BR','fixed default works without source');check($m['aluno']['data_nascimento']==='2010-05-10'&&$m['aluno']['sexo']==='MASCULINO','date and sex mapping');
$initial=(int)$db->row('SELECT COUNT(*) AS n FROM '.$db->table('pessoas'))['n'];$sync=$x->sync(1,kk());check($sync['novos']===1&&(int)$db->row('SELECT COUNT(*) AS n FROM '.$db->table('pessoas'))['n']===$initial,'fetch creates staging only');check($x->sync(1,kk())['existentes']===1,'refetch does not duplicate staging');
$row=$x->listing(1)['items'][0];$detail=$x->detail((int)$row['idrequerimento']);$choices=[];foreach($detail['pessoas'] as $slot=>$p){unset($p['sugestoes']);$choices[$slot]=['acao'=>'criar','dados'=>$p];}$key=kk();$payload=['versao'=>$row['versao'],'pessoas'=>$choices];$result=$x->confirm((int)$row['idrequerimento'],$payload,$key);check(count($result)===2,'review creates selected people');check($x->confirm((int)$row['idrequerimento'],$payload,$key)===$result,'confirmation retry idempotent');check((int)$db->row('SELECT COUNT(*) AS n FROM '.$db->table('alunos'))['n']===0,'no students or enrollments created');check($x->listing(1)['total']===0,'accepted records disappear from queue API');check($x->sync(1,kk())['existentes']===1&&$x->listing(1)['total']===0,'accepted records never return on fetch');$GLOBALS['response']['data'][0]['entry_id']='changed';check($x->sync(1,kk())['novos']===1,'same CPF different request ID is a distinct request');
$log=$x->importLog(1);check($log['total']===1,'accepted imports have a separate audit listing');$audit=$x->importLogDetail((int)$detail['idrequerimento']);check($audit['aprovados']['aluno']['dados']['nome']==='ALUNO API'&&$audit['aprovados']['aluno']['acao']==='criar','log preserves approved data and action');$cat->updatePerson((int)$result['aluno']['id'],['nome'=>'Nome alterado depois'],kk());check($x->importLogDetail((int)$detail['idrequerimento'])['aprovados']['aluno']['dados']['nome']==='ALUNO API','import snapshot does not change after later person edits');
$GLOBALS['http_code']=403;reject(fn()=>$x->test(),'origin HTTP error surfaced');$GLOBALS['http_code']=200;$GLOBALS['response']['data'][0]['entry_id']='124';$GLOBALS['response']['data'][0]['student']['cpf']='11144477735';$GLOBALS['response']['data'][0]['student']['name']='Segundo Aluno API';$x->sync(1,kk());$row=$x->listing(1)['items'][0];$before=(int)$db->row('SELECT COUNT(*) AS n FROM '.$db->table('pessoas'))['n'];reject(fn()=>$x->confirm((int)$row['idrequerimento'],['versao'=>$row['versao'],'pessoas'=>['aluno'=>['acao'=>'criar','dados'=>['nome'=>'Rollback API','data_nascimento'=>'2010-01-01']],'pai'=>['acao'=>'criar','dados'=>['nome'=>'Inválido','data_nascimento'=>'xxxx']]]],kk()),'invalid review rolls back entire confirmation');check((int)$db->row('SELECT COUNT(*) AS n FROM '.$db->table('pessoas'))['n']===$before,'no partial people on failure');
$GLOBALS['response']['data'][0]['student']['cpf']='52998224725';check($x->sync(1,kk())['existentes']===1,'request ID prevents repeated staging independently of CPF');unset($GLOBALS['response']['data'][0]['entry_id']);unset($GLOBALS['response']['data'][0]['student']['cpf']);check($x->sync(1,kk())['novos']===1,'requests without CPF or source ID are allowed');check($x->sync(1,kk())['existentes']===1,'canonical signature prevents duplicate fallback requests');
echo "EXTERNAL_API_OK\n";
