<?php
require __DIR__.'/coligadas.php';
use EducacionalERP\Application\Coligadas;
use EducacionalERP\Presentation\Rest\Controller;
use EducacionalERP\Application\ExportService;
$familyUser=(int)(new EducacionalERP\Infrastructure\WordPress\Accounts($db))->summary($rf2)['wp_user_id'];
$controller=new Controller($db,$access,$academic,$cat,new EducacionalERP\Application\FinanceService($db,$ops),new ExportService($db),$renew,$flow);
wp_set_current_user($familyUser);$rows=$controller->portalData($student,'finance',999999);$expected=[];foreach($access->accessibleIds($student,'finance') as $id){$r=$db->get('alunos',$id);$expected=array_merge($expected,Coligadas::within((int)$r['codcoligada'],fn()=>$controller->financeView($id,EducacionalERP\Application\SchoolSettings::current())));}
testP(count($rows)===count($expected)&&count($rows)>0,'portal reúne financeiro autorizado com período vigente de cada coligada');$academics=$controller->portalData($student,'academic',999999);testP(count(array_unique(array_column($academics,'codperiodo')))===2,'vida acadêmica consulta dois períodos locais sem seleção de coligada');
wp_set_current_user(1);$child=Coligadas::within($second,fn()=>$flow->createStudent(['nome'=>'Segundo Filho','data_nascimento'=>'2017-01-01','ra'=>'SEG2'],keyP()));$cat->link((int)$child['idaluno'],['codpessoa_responsavel'=>$rf2,'parentesco'=>'mae','responsavel_financeiro'=>1,'responsavel_academico'=>1,'pode_rematricular'=>1],keyP());wp_set_current_user($familyUser);$family=$access->students();testP(count($family)===2&&!array_filter($family,fn($s)=>isset($s['coligada'])),'dois filhos, sem rótulo ou seletor de coligada');
foreach($db->rows('SELECT * FROM '.$db->table('aluno_responsaveis').' WHERE idaluno=%d AND codpessoa_responsavel=%d',[$newStudent['idaluno'],$rf2]) as $link)$db->update('aluno_responsaveis',(int)$link['idvinculo'],['responsavel_academico'=>0]);testP(!in_array((int)$newStudent['idaluno'],$access->accessibleIds($student,'academic'),true),'vínculo financeiro não libera dados acadêmicos da outra ficha');testP(in_array((int)$newStudent['idaluno'],$access->accessibleIds($student,'finance'),true),'autorização financeira preservada');
wp_set_current_user(1);$api=new EducacionalERP\Application\IntegrationService($db,$ops,$cat);$financial=Coligadas::within(1,fn()=>$api->detail('financeiro',(int)$generated[0]['idlancamento']))['item'];$company=$db->get('coligadas',$second);foreach(['lancamento','contrato'] as $field)testP($financial[$field]['coligada_nome']===$company['nome']&&$financial[$field]['coligada_cnpj']===$company['cnpj'],'API '.$field.' envia nome e CNPJ do proprietário, independente da seleção');$export=(new ExportService($db))->student((int)$newStudent['idaluno'],$destPeriod);$contract=$export['matriculas'][0]['contratos'][0];testP(isset($contract['coligada_cnpj'],$contract['parcelas'][0]['lancamento']['coligada_cnpj']),'exportação completa inclui empresa do contrato e lançamento');
echo "PASS: portal familiar multicoligada e metadados financeiros\n";
