<?php
require __DIR__.'/payment-plans.php';
use EducacionalERP\Application\{FinanceService,EnrollmentLifecycle};
use EducacionalERP\Domain\{FinancialStatus,Input,Money};
wp_set_current_user(1);$finance=new FinanceService($db,$ops);$life=new EnrollmentLifecycle($db,$ops);$today=Input::today();$tomorrow=(new DateTimeImmutable($today))->modify('+1 day')->format('Y-m-d');$yesterday=(new DateTimeImmutable($today))->modify('-1 day')->format('Y-m-d');
$base=['status'=>'aberto','saldo_aberto'=>'100.00','vencimento'=>$today];
testP(FinancialStatus::value($base)==='em_aberto','vence hoje e permanece em aberto');testP(FinancialStatus::value(array_replace($base,['vencimento'=>$yesterday]))==='vencido','vencido pela data local');testP(FinancialStatus::value(array_replace($base,['status'=>'parcial','vencimento'=>$tomorrow]))==='em_aberto','baixa parcial mantém saldo em aberto');testP(FinancialStatus::value(array_replace($base,['saldo_aberto'=>'0.00']))==='baixado','saldo liquidado é baixado');testP(FinancialStatus::value(array_replace($base,['status'=>'cancelado','saldo_aberto'=>'0.00']))==='cancelado','cancelado não é confundido com baixado');
$titles=$db->rows('SELECT l.* FROM '.$db->table('lancamentos').' l JOIN '.$db->table('parcelas').' p ON p.idparcela=l.idparcela WHERE p.idcontrato=%d ORDER BY p.numero',[$ct]);$first=$titles[0];$id=(int)$first['idlancamento'];$contractBefore=$db->get('contratos',$ct);$parcelBefore=$db->get('parcelas',(int)$first['idparcela']);
$key=keyP();$edit=['versao'=>$first['versao'],'vencimento'=>$tomorrow,'valor_original'=>'500.00','motivo'=>'Renegociação'];$answer=$finance->edit($id,$edit,$key);testP($db->get('lancamentos',$id)['saldo_aberto']==='500.00','edição recalcula saldo e líquido');testP($answer['lancamentos'][0]['status']==='em_aberto','edição atualiza situação calculada');testP($finance->edit($id,$edit,$key)===$answer,'edição idempotente');testP($db->get('contratos',$ct)===$contractBefore&&$db->get('parcelas',(int)$first['idparcela'])===$parcelBefore,'edição preserva contrato e cronograma originais');deniedP(fn()=>$finance->edit($id,$edit,keyP()),'versão antiga impede sobrescrever');
$partial=$finance->pay($id,['valor_pago'=>'100.00','forma_pagamento'=>'pix'],keyP());$current=$db->get('lancamentos',$id);deniedP(fn()=>$finance->edit($id,['versao'=>$current['versao'],'valor_original'=>'50.00','motivo'=>'Teste'],keyP()),'valor inferior ao principal já pago é bloqueado');
$second=$db->get('lancamentos',(int)$titles[1]['idlancamento']);$before=$db->get('lancamentos',$id);deniedP(fn()=>$finance->editBatch(['lancamentos'=>[['idlancamento'=>$id,'versao'=>$before['versao']],['idlancamento'=>$second['idlancamento'],'versao'=>999]],'alteracoes'=>['valor_original'=>'600.00'],'motivo'=>'Teste lote'],keyP()),'falha de versão em lote aborta operação inteira');testP($db->get('lancamentos',$id)===$before,'primeiro título revertido após falha no segundo');
$finance->editBatch(['lancamentos'=>[['idlancamento'=>$id,'versao'=>$before['versao']],['idlancamento'=>$second['idlancamento'],'versao'=>$second['versao']]],'alteracoes'=>['valor_original'=>'600.00','vencimento'=>$today],'motivo'=>'Renegociação em lote'],keyP());testP($db->get('lancamentos',$id)['saldo_aberto']==='500.00'&&$db->get('lancamentos',(int)$second['idlancamento'])['saldo_aberto']==='600.00','lote aplica valor mantendo pagamento parcial');
// Third installment is overdue; second is fully paid; first has a future partial balance.
$third=(int)$titles[2]['idlancamento'];$db->update('lancamentos',$third,['vencimento'=>$yesterday]);$finance->pay((int)$second['idlancamento'],['valor_pago'=>'600.00','forma_pagamento'=>'pix'],keyP());$thirdBefore=$db->get('lancamentos',$third);$secondBefore=$db->get('lancamentos',(int)$second['idlancamento']);$m=$db->get('matriculas',(int)$initial['idmatricula']);$request=['versao'=>$m['versao'],'solicitante_tipo'=>'outro','solicitante_nome'=>'Solicitante','data_solicitacao'=>$today,'colegio_destino'=>'Escola destino'];$k=keyP();$life->external((int)$m['idmatricula'],$request,$k);$after=$db->get('lancamentos',$id);testP($after['status']==='cancelado'&&$after['valor_cancelado']==='500.00'&&$after['saldo_aberto']==='0.00'&&$after['valor_baixa']==='100.00','transferência cancela saldo não vencido preservando pagamento');testP($db->get('lancamentos',$third)===$thirdBefore,'transferência preserva débito vencido');testP($db->get('lancamentos',(int)$second['idlancamento'])===$secondBefore,'transferência preserva parcela baixada');testP($life->external((int)$m['idmatricula'],$request,$k)['status']==='transferencia_externa','transferência idempotente');deniedP(fn()=>$finance->edit($id,['versao'=>$after['versao'],'valor_original'=>'700.00','motivo'=>'Teste'],keyP()),'título cancelado não pode ser editado');
// Cancellation also covers ordinary initial enrollments and future titles.
$futureTitles=$db->rows('SELECT l.* FROM '.$db->table('lancamentos').' l JOIN '.$db->table('parcelas').' p ON p.idparcela=l.idparcela WHERE p.idcontrato=%d',[$pending]);$futureM=$db->get('matriculas',(int)$result['idmatricula']);$life->cancel((int)$futureM['idmatricula'],['versao'=>$futureM['versao']],keyP());foreach($futureTitles as $title)testP($db->get('lancamentos',(int)$title['idlancamento'])['status']==='cancelado','cancelamento de rematrícula cancela título futuro');
wp_set_current_user($staff);deniedP(fn()=>$finance->editBatch(['lancamentos'=>[['idlancamento'=>$third,'versao'=>$thirdBefore['versao']]],'alteracoes'=>['valor_original'=>'700.00'],'motivo'=>'Teste'],keyP()),'Secretaria sem permissão não edita financeiro');
echo "PASS: gestão financeira concluída\n";
