<?php
require __DIR__.'/payment-plans.php';
use EducacionalERP\Application\IntegrationService;
$integration=new IntegrationService($db,$ops,$cat);wp_set_current_user(1);
$current=$db->get('turmas',$t);$enrollmentBefore=$db->get('matriculas',(int)$initial['idmatricula']);$contractBefore=$db->get('contratos',$ct);
$cat->classRenewal($t,['versao'=>$current['versao'],'idturma_proxima'=>null],keyP());$current=$db->get('turmas',$t);$cat->classRenewal($t,['versao'=>$current['versao'],'idturma_proxima'=>$future],keyP());testP((int)$db->get('turmas',$t)['idturma_proxima']===$future,'turma ocupada aceita alteração isolada da rematrícula');testP($db->get('matriculas',(int)$initial['idmatricula'])===$enrollmentBefore&&$db->get('contratos',$ct)===$contractBefore,'destino alterado não muda matrícula nem contrato atuais');deniedP(fn()=>$cat->classRenewal($t,['versao'=>$current['versao'],'idturma_proxima'=>null],keyP()),'destino exige versão atual');
$detail=$integration->detail('alunos',$student)['item'];testP($detail['pessoa']['nome']!==''&&count($detail['mae'])===1&&count($detail['pai'])===1,'API aluno inclui pessoa, pai, mãe e dados completos');testP(isset($detail['mae'][0]['pessoa']['data_nascimento'])&&array_key_exists('rg',$detail['pessoa']),'API inclui campos pessoais e atribuições dos vínculos');
$collection=$integration->collection('alunos',['limit'=>1]);testP(count($collection['items'])===1&&$collection['next_cursor']!==null,'paginação por cursor');$second=$integration->collection('alunos',['limit'=>1,'cursor'=>$collection['next_cursor']]);testP($second['items'][0]['idaluno']!==$collection['items'][0]['idaluno'],'cursor não repete aluno');testP($integration->collection('alunos',['ra'=>'00077'])['items'][0]['idaluno']===(string)$student,'filtro de RA preserva zeros');
$enrollment=$integration->detail('matriculas',(int)$initial['idmatricula'])['item'];testP(isset($enrollment['aluno']['vinculos'],$enrollment['turma'],$enrollment['curso'],$enrollment['turno'],$enrollment['contratos'][0]['parcelas'][0]['lancamentos']),'API matrícula tem estrutura e contrato detalhados');
$financial=$integration->collection('financeiro',['codperiodo'=>$period,'idaluno'=>$student,'status'=>'vencido']);testP(count($financial['items'])===3&&isset($financial['items'][0]['aluno'],$financial['items'][0]['matricula']['turma'],$financial['items'][0]['lancamento']['baixas']),'API financeiro retorna aluno, turma e lançamento detalhado');testP($integration->collection('financeiro',['status'=>'cancelado'])['items']===[],'filtro cancelados não retorna outros títulos');deniedP(fn()=>$integration->collection('financeiro',['status'=>'invalido']),'situação inválida bloqueada');deniedP(fn()=>$integration->collection('alunos',['limit'=>51]),'paginação tem limite');
$data=['pessoa'=>['nome'=>'Integracao Aluno','data_nascimento'=>'2015-01-01','rg'=>'1234'],'aluno'=>['ra'=>'API-0001','tipo_aluno'=>'AEE'],'vinculos'=>[['parentesco'=>'pai','responsavel_financeiro'=>true,'pessoa'=>['nome'=>'Integracao Pai','data_nascimento'=>'1980-01-01']],['parentesco'=>'mae','responsavel_academico'=>true,'pessoa'=>['nome'=>'Integracao Mae','data_nascimento'=>'1981-01-01']]]];$key=keyP();$created=$integration->createStudent($data,$key);testP($created['item']['tipo_aluno']==='AEE'&&count($created['item']['pai'])===1&&count($created['item']['mae'])===1,'recebimento cria aluno e família na mesma transação');testP($integration->createStudent($data,$key)===$created,'reenvio não duplica aluno nem pessoas');$count=count($db->rows('SELECT * FROM '.$db->table('pessoas')));$invalid=$data;$invalid['pessoa']['nome']='Integracao Falha';$invalid['aluno']['ra']='API-FALHA';$invalid['vinculos'][0]['pessoa']['nome']='Falha Pai Novo';$invalid['vinculos'][1]['pessoa']['nome']='Falha Mae Nova';$invalid['vinculos'][1]['parentesco']='invalido';deniedP(fn()=>$integration->createStudent($invalid,keyP()),'vínculo inválido interrompe recebimento');testP(count($db->rows('SELECT * FROM '.$db->table('pessoas')))===$count,'falha reverte aluno, pessoas e vínculos');
wp_set_current_user($rfUser);deniedP(fn()=>$integration->detail('alunos',$student),'responsável não acessa API global de integração');deniedP(fn()=>$integration->createStudent($data,keyP()),'responsável não grava pela integração');echo "PASS: APIs de integração concluídas\n";
