const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const code=fs.readFileSync(require('path').join(__dirname,'../assets/workflow.js'),'utf8'),wait=()=>new Promise(r=>setTimeout(r,20));
async function boot(screen,query='',admin=true){const calls=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))throw e;});const dom=new JSDOM(`<main><div data-erp-screen="${screen}"></div></main>`,{url:'https://example.test/portal?erp_tela='+screen+query,runScripts:'dangerously',virtualConsole:vc});const w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.EDERP={root:'https://example.test/api/',front:true,portal:'https://example.test/portal',period:7,nonce:'test',caps:{admin,academic:true,people:true}};
w.fetch=async(raw,options={})=>{const u=new URL(raw),route=u.pathname.slice(5);const body=options.body?JSON.parse(options.body):null;calls.push({route,u,body});let data;
if(body)data={total:2,codperiodo:Number(body.codperiodo),excluido:true};
else if(route==='turmas/9/plano')data={idplano:'4',versao:'2',nome:'Anuidade',valor_anuidade:'1200.00'};
else if(route.startsWith('cadastros/periodos_letivos/'))data={codperiodo_proximo:8,codigo:'2027',descricao:'Próximo'};
else if(route==='colegio')data={data:{nome:'ESCOLA TESTE',logo_id:0,cor_primaria:'#087862',cor_superficie:'#ffffff',cor_texto:'#193d38',cor_destaque:'#26ba9b'},fields:{nome:'Nome do colégio'},colors:{cor_primaria:'Botões',cor_superficie:'Cartões',cor_texto:'Texto',cor_destaque:'Destaque'},version:'v1',customizer_url:'https://example.test/customize'};
else if(route==='configuracoes')data={codperiodo:7,periodos:[{codperiodo:7,codigo:'2026',descricao:'Atual'},{codperiodo:8,codigo:'2027',descricao:'Próximo'}]};
else if(route==='matriculas/filtros')data={cursos:[{idcurso:4,nome:'Fundamental'}],turnos:[{idturno:5,nome:'Manhã'}],turmas:[{idturma:9,codperiodo:7,idcurso:4,idturno:5,nome:'Turma A'},{idturma:10,codperiodo:8,idcurso:4,idturno:5,nome:'Turma B'}]};
else if(route==='matriculas')data={items:[{idmatricula:1,idaluno:2,ra:'0002',aluno:'Sofia',turma:'Turma A',turno:'Manhã',curso:'Fundamental',periodo:'2026',versao:3,status:'ativa'}],total:1};
else if(route==='secretaria/alunos')data={items:[{idaluno:2,nome:'Sofia',ra:'0002',ativo:1},{idaluno:3,nome:'João',ra:'0003',ativo:1}],total:2};
else if(route.startsWith('opcoes/'))data={items:route.endsWith('periodos_letivos')?[{id:7,label:'2026'}]:route.endsWith('turmas')?[{id:9,label:'Turma A'}]:[{id:4,label:'Opção'}],more:false};
else data={items:[],total:0};return {ok:true,json:async()=>data};};w.eval(fs.readFileSync(require('path').join(__dirname,'../assets/modals.js'),'utf8'));w.eval(code);await wait();await wait();return {dom,w,d:w.document,calls};}
function click(x,text){const b=[...x.d.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(b,text);b.click();}
(async()=>{
let x=await boot('matriculas');let req=x.calls.find(c=>c.route==='matriculas');assert.equal(req.u.searchParams.get('codperiodo'),'7');assert.equal(x.d.querySelector('[data-erp-screen]').firstChild.textContent,'Matricular aluno');for(const text of ['RA','Aluno','Turma','Turno','Curso'])assert.ok([...x.d.querySelectorAll('th')].some(t=>t.textContent===text));console.log('PASS: abre lista do período atual com botão superior e colunas solicitadas');
const period=x.d.querySelector('[name=codperiodo]');period.value='8';period.dispatchEvent(new x.w.Event('change'));assert.equal(x.d.querySelector('[name=idturma]').options.length,2);assert.equal(x.d.querySelector('[name=idturma]').options[1].textContent,'Turma B');x.d.querySelector('[name=search]').value='0002';x.d.querySelector('form').requestSubmit();await wait();req=x.calls.filter(c=>c.route==='matriculas').at(-1);assert.equal(req.u.searchParams.get('codperiodo'),'8');assert.equal(req.u.searchParams.get('search'),'0002');console.log('PASS: filtros de turma dependem do período e enviam busca');
click(x,'Excluir');assert.ok(x.d.querySelector('dialog[open]'));x.d.querySelector('dialog [name=motivo]').value='Correção de duplicidade';x.d.querySelector('dialog form').requestSubmit();await wait();req=x.calls.find(c=>c.route==='exclusoes/matriculas/1');assert.equal(req.body.versao,3);assert.equal(req.body.motivo,'Correção de duplicidade');assert.equal(x.d.querySelector('dialog'),null);console.log('PASS: exclusão pede motivo e envia versão do registro');x.dom.window.close();
x=await boot('matriculas','',false);assert.ok(![...x.d.querySelectorAll('button')].some(b=>b.textContent==='Excluir'));console.log('PASS: perfil não administrador não recebe exclusão');x.dom.window.close();
x=await boot('matriculas','&novo=1');assert.equal(x.d.querySelectorAll('.erp-picker input[type=search]').length,0);assert.equal(x.d.querySelectorAll('.erp-picker select').length,4);assert.equal(x.d.querySelector('dialog[open] [name=codperiodo]').value,'7');for(const name of ['idcurso','idturno']){x.d.querySelector('dialog[open] [name='+name+']').value='4';x.d.querySelector('dialog[open] [name='+name+']').dispatchEvent(new x.w.Event('change'));}await wait();x.d.querySelector('dialog[open] [name=idturma]').value='9';x.d.querySelector('dialog[open] [name=idturma]').dispatchEvent(new x.w.Event('change'));await wait();x.d.querySelector('dialog[open] [name=primeiro_vencimento]').value='2027-01-10';click(x,'Selecionar alunos desta página');x.d.querySelector('dialog[open] form').requestSubmit();await wait();req=x.calls.find(c=>c.route==='matriculas/lote');assert.deepEqual(req.body,{codperiodo:'7',idturma:'9',alunos:['2','3'],idplano:'4',plano_versao:'2',quantidade_parcelas:'12',primeiro_vencimento:'2027-01-10',desconto_incondicional_total:'0.00',termo:'Contrato de prestação de serviços educacionais.'});assert.equal(x.d.querySelector('dialog[open]'),null);console.log('PASS: lote envia vários alunos para período e turma escolhidos');x.dom.window.close();
x=await boot('academico');assert.ok(x.d.querySelector('[name=codperiodo_proximo]'));click(x,'Planos de pagamento');await wait();assert.ok(x.d.querySelector('form [name=codperiodo]'));click(x,'Turmas');await wait();assert.equal(x.d.querySelectorAll('.erp-picker input[type=search]').length,0);assert.equal(x.d.querySelectorAll('.erp-picker select').length,7);assert.ok(x.d.querySelector('[name=idturma_proxima]'));assert.equal(x.calls.filter(c=>c.route==='opcoes/planos_pagamento').at(-1).u.searchParams.get('codperiodo'),'7');assert.equal(x.d.querySelector('[name=destino_periodo]'),null);assert.equal(x.calls.filter(c=>c.route==='opcoes/turmas').at(-1).u.searchParams.get('codperiodo'),'8');x.d.querySelector('[name=filtro_curso]').value='4';x.d.querySelector('[name=filtro_curso]').dispatchEvent(new x.w.Event('change'));await wait();assert.equal(x.calls.filter(c=>c.route==='cadastros/turmas').at(-1).u.searchParams.get('idcurso'),'4');click(x,'Todos os cursos');await wait();assert.equal(x.calls.filter(c=>c.route==='cadastros/turmas').at(-1).u.searchParams.get('idcurso'),'');console.log('PASS: próximo período no cadastro e turma de destino filtrada automaticamente');x.dom.window.close();
x=await boot('configuracoes');assert.equal(x.d.querySelector('[name=codperiodo]').value,'7');x.d.querySelector('[name=codperiodo]').value='8';x.d.querySelector('form').requestSubmit();await wait();assert.equal(x.calls.find(c=>c.body)?.body.codperiodo,'8');assert.equal(x.w.EDERP.period,8);console.log('PASS: configuração salva período e atualiza contexto');x.dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
