<?php
require __DIR__.'/external-people-api.php';
$field=$s->save(['nome'=>'Dado apenas da API','chave'=>'api_oculto','tipo'=>'texto','exibir_pessoa'=>0,'exibir_aluno'=>0,'idgrupo'=>''],kk());
$GLOBALS['response']['data'][0]['entry_id']='hidden-request';$GLOBALS['response']['data'][0]['student']['cpf']='52998224725';$GLOBALS['response']['data'][0]['student']['extra']='dado recebido';$GLOBALS['response']['data'][0]['student']['second']='novo mapeamento';$x->sync(1,kk());$pending=$x->listing(1)['items'][0];check(!isset($x->detail((int)$pending['idrequerimento'])['pessoas']['aluno']['campos_adicionais']['api_oculto']),'pending initially uses previous mapping');
$maps[]=['pessoa'=>'aluno','origem'=>'student.extra','destino'=>'extra:api_oculto'];$x->save(['url'=>'https://crm.example.test/api?per_page=50','usuario'=>'api','senha'=>'','caminho_lista'=>'data','campo_id'=>'entry_id','mapeamento'=>$maps],kk());$detail=$x->detail((int)$pending['idrequerimento']);check($detail['pessoas']['aluno']['campos_adicionais']['api_oculto']==='dado recebido','mapping refresh exposes hidden field for conference');
$maps[]=['pessoa'=>'aluno','origem'=>'student.second','destino'=>'rg'];$x->save(['url'=>'https://crm.example.test/api?per_page=50','usuario'=>'api','senha'=>'','caminho_lista'=>'data','campo_id'=>'entry_id','mapeamento'=>$maps],kk());$detail=$x->detail((int)$pending['idrequerimento']);check($detail['pessoas']['aluno']['rg']==='novo mapeamento','saved mapping reapplies original source');
$person=(int)$detail['pessoas']['aluno']['sugestoes'][0]['codpessoa'];$result=$x->confirm((int)$pending['idrequerimento'],['versao'=>$detail['versao'],'pessoas'=>['aluno'=>['acao'=>'vincular','codpessoa'=>$person],'pai'=>['acao'=>'ignorar']]],kk());check($s->decorate($db->get('pessoas',$person))['campos_adicionais']['api_oculto']==='DADO RECEBIDO','hidden mapped data imports into existing person');check($x->sync(1,kk())['existentes']===1&&$x->importLogDetail((int)$pending['idrequerimento'])['aprovados']['aluno']['dados']['campos_adicionais']['api_oculto']==='DADO RECEBIDO','accepted import and frozen log survive repeated fetch');
// Pre-upgrade pending requests have no source snapshot: fetching again fills them.
$GLOBALS['response']['data'][0]['entry_id']='legacy-pending';$x->sync(1,kk());$last=$x->listing(1)['items'][0];$db->update('api_requerimentos',(int)$last['idrequerimento'],['origem_json'=>null,'pessoas_json'=>wp_json_encode(['aluno'=>['nome'=>'old']])]);$x->sync(1,kk());check($x->detail((int)$last['idrequerimento'])['pessoas']['aluno']['campos_adicionais']['api_oculto']==='dado recebido','refetch refreshes legacy pending without duplicate');
$GLOBALS['response']['data'][0]['student']['extra']=['Psicólogo','Psicopedagoga','Fonoaudiólogo'];$x->sync(1,kk());$detail=$x->detail((int)$last['idrequerimento']);check($detail['pessoas']['aluno']['campos_adicionais']['api_oculto']==="Psicólogo\nPsicopedagoga\nFonoaudiólogo",'API array maps every item on its own line');$x->confirm((int)$last['idrequerimento'],['versao'=>$detail['versao'],'pessoas'=>['aluno'=>['acao'=>'vincular','codpessoa'=>$person],'pai'=>['acao'=>'ignorar']]],kk());check($s->decorate($db->get('pessoas',$person))['campos_adicionais']['api_oculto']==="PSICÓLOGO\nPSICOPEDAGOGA\nFONOAUDIÓLOGO",'imported array preserves all lines');
echo "MAPPED_HIDDEN_IMPORT_OK\n";
