const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const code=fs.readFileSync(require('path').join(__dirname,'../assets/workflow.js'),'utf8'),wait=()=>new Promise(r=>setTimeout(r,20));
async function boot(screen,query='',admin=true){const calls=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))throw e;});const dom=new JSDOM(`<main><div data-erp-screen="${screen}"></div></main>`,{url:'https://example.test/portal?erp_tela='+screen+query,runScripts:'dangerously',virtualConsole:vc});const w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.EDERP={root:'https://example.test/api/',front:true,portal:'https://example.test/portal',period:7,nonce:'test',caps:{admin,academic:true,people:true}};
w.fetch=async(raw,options={})=>{const u=new URL(raw),route=u.pathname.slice(5);const body=options.body?JSON.parse(options.body):null;calls.push({route,u,body});let data;
if(body)data={total:2,codperiodo:Number(body.codperiodo),excluido:true};
else if(route==='ofertas-rematricula')data={items:[{idoferta:1,codperiodo_destino:7,idcurso_origem:4,idcurso_destino:4,periodo:'2026',curso_origem:'Fundamental',curso_destino:'Fundamental',turmas:[{idturma:9,nome:'Turma A'}],data_abertura:'2026-01-01',data_encerramento:'2027-01-01',numero_parcelas:12,primeiro_vencimento:'2027-01-10',texto_termo:'Termo',versao_termo:'1',ativo:1,version:'v1',utilizacoes:0,situacao:'Disponível'}],total:1};
else if(route==='turmas/9/plano')data={idplano:'4',versao:'2',nome:'Anuidade',valor_anuidade:'1200.00'};
else if(route.startsWith('cadastros/periodos_letivos/'))data={codperiodo_proximo:8,codigo:'2027',descricao:'Próximo'};
else if(route==='colegio')data={data:{nome:'ESCOLA TESTE',logo_id:0,cor_primaria:'#087862',cor_superficie:'#ffffff',cor_texto:'#193d38',cor_destaque:'#26ba9b'},fields:{nome:'Nome do colégio'},colors:{cor_primaria:'Botões',cor_superficie:'Cartões',cor_texto:'Texto',cor_destaque:'Destaque'},version:'v1',customizer_url:'https://example.test/customize'};
else if(route==='configuracoes')data={codperiodo:7,periodos:[{codperiodo:7,codigo:'2026',descricao:'Atual'},{codperiodo:8,codigo:'2027',descricao:'Próximo'}]};
else if(route==='matriculas/filtros')data={cursos:[{idcurso:4,nome:'Fundamental'}],turnos:[{idturno:5,nome:'Manhã'}],turmas:[{idturma:9,codperiodo:7,idcurso:4,idturno:5,nome:'Turma A'},{idturma:10,codperiodo:8,idcurso:4,idturno:5,nome:'Turma B'}]};
else if(route==='matriculas')data={items:[{idmatricula:1,idaluno:2,ra:'0002',aluno:'Sofia',turma:'Turma A',turno:'Manhã',curso:'Fundamental',periodo:'2026',versao:3,status:'ativa'}],total:1};
else if(route==='secretaria/alunos')data={items:[{idaluno:2,nome:'Sofia',ra:'0002',ativo:1},{idaluno:3,nome:'João',ra:'0003',ativo:1}],total:2};
else if(route.startsWith('opcoes/'))data={items:route.endsWith('periodos_letivos')?[{id:7,label:'2026'}]:route.endsWith('turmas')?[{id:9,label:'Turma A'},{id:10,label:'Turma B'}]:[{id:4,label:'Opção'}],more:false};
else data={items:[],total:0};return {ok:true,json:async()=>data};};w.eval(fs.readFileSync(require('path').join(__dirname,'../assets/modals.js'),'utf8'));w.eval(code);await wait();await wait();return {dom,w,d:w.document,calls};}
function click(x,text){const b=[...x.d.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(b,text);b.click();}
(async()=>{
let x=await boot('rematriculas');assert.ok(x.d.body.textContent.includes('Disponível'));click(x,'Nova oferta em lote');await wait();let f=x.d.querySelector('dialog[open] form');for(const [name,value]of [['codperiodo_destino','7'],['idcurso_origem','4'],['idcurso_destino','4']]){f.querySelector('[name='+name+']').value=value;f.querySelector('[name='+name+']').dispatchEvent(new x.w.Event('change'));}await wait();click(x,'Selecionar todas');assert.equal(f.querySelectorAll('input[type=checkbox]:checked').length,2);for(const [name,value]of [['data_abertura','2026-01-01'],['data_encerramento','2027-01-01'],['primeiro_vencimento','2027-01-10'],['texto_termo','Termo']])f.querySelector('[name='+name+']').value=value;f.requestSubmit();await wait();let req=x.calls.find(c=>c.route==='ofertas-rematricula'&&c.body);assert.deepEqual(req.body.turmas,['9','10']);assert.equal(x.d.querySelector('dialog[open]'),null);console.log('PASS: seleção de várias turmas e envio em lote pelo modal');
click(x,'Editar');await wait();f=x.d.querySelector('dialog[open] form');assert.equal(f.querySelector('[name=texto_termo]').value,'Termo');f.querySelector('[name=data_encerramento]').value='2028-01-01';f.requestSubmit();await wait();req=x.calls.find(c=>c.route==='ofertas-rematricula/1'&&c.body);assert.equal(req.body.version,'v1');assert.equal(req.body.data_encerramento,'2028-01-01');console.log('PASS: edição carregada com versão e datas');
click(x,'Excluir');await wait();f=x.d.querySelector('dialog[open] form');f.querySelector('[name=motivo]').value='Oferta duplicada';f.requestSubmit();await wait();req=x.calls.find(c=>c.route==='ofertas-rematricula/1/excluir');assert.equal(req.body.version,'v1');assert.equal(req.body.motivo,'Oferta duplicada');console.log('PASS: exclusão em modal exige motivo');x.dom.window.close();
x=await boot('rematriculas','',false);assert.ok(![...x.d.querySelectorAll('button')].some(b=>['Editar','Excluir'].includes(b.textContent)));console.log('PASS: edição e exclusão restritas ao administrador');x.dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
