const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path');const source=fs.readFileSync(path.join(__dirname,'../assets/app.js'),'utf8'),wait=()=>new Promise(r=>setTimeout(r,20));
async function boot(view,html,caps={}){const calls=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{throw e});const dom=new JSDOM(`<main class="journey-content" data-journey-screen="${view}">${html}</main>`,{url:'https://example.test/portal?erp_tela='+view+'&erp_periodo=todos',runScripts:'dangerously',virtualConsole:vc});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.dispatchEvent(new w.Event('close'));};w.EDERP={root:'https://example.test/api/',nonce:'test',period:'todos',currentPeriod:7,caps};
w.fetch=async(raw,opt={})=>{const u=new URL(raw),route=u.pathname.slice(5);calls.push({route,u,body:opt.body&&JSON.parse(opt.body)});let d;
if(opt.method==='POST')d={salvo:true};else if(route==='configuracoes')d={codperiodo:7,periodos:[{codperiodo:7,codigo:'2026',descricao:'Atual'},{codperiodo:8,codigo:'2027',descricao:'Futuro'}]};
else if(route==='me/alunos')d=[{idaluno:1,nome:'Sofia',ra:'0001'}];
else if(route==='alunos/1/ofertas-rematricula')d=[{idoferta:2,idmatricula_origem:3,versao_termo:'1',texto_termo:'Termo',numero_parcelas:12,primeiro_vencimento:'2027-01-31',turmas:[{idturma:9,nome:'Turma futura',plano:{idplano:4,versao:2,nome:'Plano Anual',valor_anuidade:'1500.00'}}]}];
else if(route==='financeiro/pendentes')d={items:[{idcontrato:6,numero:'CT-6',ra:'0001',aluno:'Sofia',turma:'Turma futura',periodo:'2027',plano:'Anual',valor_original_total:'1500.00',valor_liquido_total:'1500.00',quantidade_parcelas:5,primeiro_vencimento:'2027-01-31'}],total:1};else d=[];return {ok:true,json:async()=>d};};w.eval(fs.readFileSync(path.join(__dirname,'../assets/modals.js'),'utf8'));w.eval(source);await wait();await wait();return {dom,w,d:w.document,calls};}
(async()=>{
let x=await boot('meus_estudos','<section data-ederp-portal="academic"></section>');assert.equal(x.d.querySelector('.erp-period-bar'),null);assert.equal(x.calls.find(c=>c.route==='alunos/1/matriculas').u.searchParams.get('codperiodo'),'7');console.log('PASS: portal do aluno não exibe filtro e usa vigente mesmo com URL alterada');x.dom.window.close();
x=await boot('renovacao','<section data-ederp-portal="renew"></section>');assert.equal(x.d.querySelector('.erp-period-bar'),null);assert.ok(x.d.body.textContent.includes('1500.00'));x.d.querySelector('.erp-modal-trigger').click();const f=x.d.querySelector('dialog[open] form');assert.equal(f.querySelector('select[name=idturma]'),null);assert.equal(f.querySelector('input[name=idturma]').type,'hidden');assert.match(f.textContent,/Destino definido pela escola/);f.querySelector('[name=quantidade_parcelas]').value='5';f.querySelector('[name=aceite]').checked=true;f.requestSubmit();await wait();const req=x.calls.find(c=>c.route==='rematriculas');assert.equal(req.body.idplano,'4');assert.equal(req.body.plano_versao,'2');assert.equal(req.body.quantidade_parcelas,'5');assert.equal(req.body.valor_total,undefined);console.log('PASS: rematrícula envia escolha de parcelas e versão do plano exibido');x.dom.window.close();
x=await boot('financeiro','<section data-ederp-pending></section>',{periods:true,generate:true});assert.ok(x.d.querySelector('.erp-period-bar'));[...x.d.querySelectorAll('button')].find(b=>b.textContent==='Gerar parcelas').click();assert.ok(x.d.querySelector('dialog'));[...x.d.querySelectorAll('button')].find(b=>b.textContent==='Confirmar geração').click();await wait();assert.ok(x.calls.some(c=>c.route==='contratos/6/parcelas'&&c.body.confirmado));console.log('PASS: Financeiro confirma geração do contrato pendente');x.dom.window.close();
x=await boot('meu_financeiro','<section data-ederp-portal="finance"></section>',{periods:true});assert.equal(x.d.querySelector('.erp-period-bar'),null);assert.equal(x.calls.find(c=>c.route==='alunos/1/financeiro').u.searchParams.get('codperiodo'),'7');console.log('PASS: área pessoal financeira permanece no vigente mesmo para usuário com papel operacional');x.dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
