const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),wait=()=>new Promise(r=>setTimeout(r,25));
const assets=path.join(__dirname,'../assets');
(async()=>{
let dom=new JSDOM('<div data-erp-screen="academico"></div>',{runScripts:'dangerously',url:'https://example.test/portal'}),w=dom.window,d=w.document,calls=[];
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.EDERP={root:'https://example.test/api/',period:7,caps:{admin:true}};
w.fetch=async(raw,opt={})=>{const route=new URL(raw).pathname.slice(5),body=opt.body&&JSON.parse(opt.body);calls.push({route,body});return {ok:true,json:async()=>body?{turmas:2,planos:1,codperiodo_destino:8}:route.startsWith('opcoes/')?{items:[{id:7,label:'2026'},{id:8,label:'2027'}],more:false}:{items:[],total:0}};};
const click=text=>{const b=[...d.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);b.click();};
for(const file of ['modals.js','workflow.js'])w.eval(fs.readFileSync(path.join(assets,file),'utf8'));await wait();click('Copiar para próximo período');await wait();let f=d.querySelector('dialog[open] form');assert.ok(f);for(const [k,v] of Object.entries({codigo:'2027',descricao:'Futuro',data_inicio:'2027-01-01',data_fim:'2027-12-31'}))f.querySelector('[name='+k+']').value=v;f.requestSubmit();await wait();let req=calls.find(c=>c.body);assert.equal(req.route,'periodos/copiar');assert.equal(req.body.codperiodo_origem,'7');assert.equal(req.body.novo_periodo.codigo,'2027');assert.equal(req.body.codperiodo_destino,undefined);assert.match(d.body.textContent,/2 turmas e 1 planos/);
click('Copiar para próximo período');await wait();f=d.querySelector('dialog[open] form');f.querySelector('[name=modo]').value='existente';f.querySelector('[name=modo]').dispatchEvent(new w.Event('change'));f.querySelector('[name=codperiodo_destino]').value='8';f.requestSubmit();await wait();req=calls.filter(c=>c.body).at(-1);assert.equal(req.body.codperiodo_destino,'8');assert.equal(req.body.novo_periodo,undefined);console.log('PASS: cópia abre em modal e envia destino novo ou existente');dom.window.close();
dom=new JSDOM('<div data-erp-screen="importacao"></div>',{runScripts:'dangerously',url:'https://example.test/portal'});w=dom.window;d=w.document;calls=[];w.TextDecoder=TextDecoder;w.EDERP={root:'https://example.test/api/',caps:{admin:true}};w.fetch=async(url,opt)=>{calls.push({url,body:JSON.parse(opt.body)});return {ok:true,json:async()=>({status:'criado'})};};w.eval(fs.readFileSync(path.join(assets,'import.js'),'utf8'));const type=d.querySelector('select');type.value='turmas';type.dispatchEvent(new w.Event('change'));
const csv='codigo_periodo;codigo;nome;codigo_curso;codigo_turno;capacidade;codigo_plano\r\n2027;01A;PRIMEIRO A;EF;M;30;AN27\r\n';Object.defineProperty(d.querySelector('input[type=file]'),'files',{value:[{size:csv.length,arrayBuffer:async()=>new TextEncoder().encode(csv).buffer}]});click('Ler arquivo e mapear colunas');await wait();click('Conferir prévia');assert.equal(calls.length,0);click('Importar 1 registros');await wait();assert.equal(calls[0].url,'https://example.test/api/importacao/turmas');assert.equal(calls[0].body.codigo,'01A');assert.equal(calls[0].body.codigo_plano,'AN27');assert.match(d.body.textContent,/1 criados/);console.log('PASS: importação mapeia CSV, exibe prévia e preserva códigos');dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
