const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');const base=require('path').join(__dirname,'../');const read=p=>fs.readFileSync(base+p,'utf8');const sleep=()=>new Promise(r=>setTimeout(r,20));
async function open(view){const fixture=JSON.parse(fs.readFileSync(require('path').join(__dirname,'fixtures/portal-'+view+'.json')));const dom=new JSDOM(fixture.html,{url:'https://example.test/portal-journey/?erp_tela='+view,runScripts:'dangerously'});const w=dom.window;Object.assign(w,fixture.globals);const calls=[];w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.fetch=async(url,opt={})=>{calls.push({url,opt});let out;const path=new URL(url,'https://example.test').pathname;
if(url.includes('localidades/'))out=JSON.parse(read('assets/localidades/'+url.split('/').pop()));
else if(path.endsWith('/estados-civis'))out=[{idestado_civil:1,nome:'SOLTEIRO'}];
else if(opt.method==='POST')out={salvo:true,versao:'2'};
else if(path.endsWith('/painel'))out={cards:[{menu:'pessoas',titulo:'Pessoas cadastradas',total:100}],alunos:[]};
else if(path.endsWith('/me/perfil'))out={pessoa:{codpessoa:'1',nome:'Paulo Maeda',cpf:'',data_nascimento:'1980-01-01',email:'a@example.test',pais:'BR',estado:'SP',cidade:'São Paulo',versao:'1'},conta:{user_login:'paulo.maeda',roles:['erp_pessoa']},redefinir_senha:'https://example.test/recuperar'};
else if(path.endsWith('/perfis'))out={roles:[{slug:'erp_secretaria',nome:'Secretaria',menus:['pessoas'],custom:false},{slug:'erp_custom_atendimento',nome:'Atendimento',menus:[],custom:true}],menus:{pessoas:'Pessoas',alunos:'Alunos'}};
else if(path.includes('/opcoes/'))out={items:[{id:'2',label:'Maria Silva'}],more:false};
else out={items:[],total:0};return {ok:true,json:async()=>out};};
for(const f of ['person-fields','app','workflow','portal'])w.eval(read('assets/'+f+'.js'));await sleep();await sleep();return {dom,w,d:w.document,calls};}
(async()=>{let x=await open('inicio');assert.match(x.d.querySelector('h1').textContent,/Olá, Paulo/);assert.equal(x.d.querySelectorAll('.journey-bottom a').length,3);assert.ok([...x.d.querySelectorAll('.journey-menu a')].every(a=>!a.href.includes('wp-admin')));console.log('PASS: dashboard e navegação apontam para páginas front-end');x.d.querySelector('.journey-bottom button').click();assert.equal(x.d.querySelector('dialog').open,true);x.d.querySelector('[data-close-menu]').click();assert.equal(x.d.querySelector('dialog').open,false);console.log('PASS: menu mobile abre e fecha');x.w.dispatchEvent(new x.w.Event('offline'));assert.equal(x.d.querySelector('.journey-offline').hidden,false);console.log('PASS: portal informa indisponibilidade de conexão');x.dom.window.close();
x=await open('perfil');const f=x.d.querySelector('form');assert.equal(f.querySelector('[name=codpessoa_origem]'),null);assert.equal(f.querySelector('[name=roles]'),null);f.querySelector('[name=nome]').value='Paulo Atualizado';f.requestSubmit();await sleep();const post=x.calls.find(c=>c.opt.method==='POST');assert.ok(post.url.endsWith('me/perfil'));const body=JSON.parse(post.opt.body);assert.equal(body.nome,'Paulo Atualizado');assert.equal(body.versao,'1');assert.equal(body.codpessoa,undefined);assert.equal(body.estado,'SP');console.log('PASS: perfil envia somente dados pessoais ao endpoint próprio');assert.match(x.d.querySelector('.erp-feedback').textContent,/salvas/);x.dom.window.close();
x=await open('perfis');const form=x.d.querySelector('.journey-permission-grid');form.querySelector('input').checked=false;form.requestSubmit();await sleep();const save=x.calls.find(c=>c.opt.method==='POST');assert.ok(save.url.endsWith('perfis/menus'));assert.deepEqual(JSON.parse(save.opt.body),{role:'erp_secretaria',menus:[]});console.log('PASS: matriz salva revogação de menu');x.dom.window.close();
x=await open('pessoas');assert.ok(x.d.querySelector('[name=rg]'));assert.ok(x.d.querySelector('[name=cidade]'));assert.ok([...x.d.querySelectorAll('a')].filter(a=>a.href.includes('erp_tela')).length);console.log('PASS: cadastro ampliado funciona dentro do portal');x.dom.window.close();
x=await open('alunos');assert.ok([...x.d.querySelectorAll('a')].some(a=>a.textContent==='Cadastrar aluno'&&a.href.includes('erp_tela=alunos')&&a.href.includes('novo=1')));console.log('PASS: criar aluno mantém fluxo no front-end');x.dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
