<?php
require __DIR__.'/coligadas.php';
use EducacionalERP\Application\PreviousHistory;
wp_set_current_user(1);$history=new PreviousHistory($db);$types=EducacionalERP\Application\Coligadas::within(1,fn()=>$history->typeSave(['nome'=>'Base nacional comum'],keyP()));$type=(int)$types['idtipo_disciplina'];
$body=['escola_nome'=>'Escola antiga','escola_cnpj'=>'04.252.011/0001-10','rua'=>'Rua antiga','numero'=>'10','cidade'=>'Curitiba','estado'=>'PR','pais'=>'Brasil','anos'=>[['periodo_letivo'=>'2024','ano_letivo'=>'2024','serie'=>'4 ano','curso'=>'Fundamental 1','disciplinas'=>[['nome'=>'Matemática','nota_final'=>'8,5','idtipo_disciplina'=>$type],['nome'=>'Artes','nota_final'=>'APTO','idtipo_disciplina'=>$type]]],['periodo_letivo'=>'2025','ano_letivo'=>'2025','serie'=>'5 ano','curso'=>'Fundamental 1','disciplinas'=>[['nome'=>'Português','nota_final'=>'9.0','idtipo_disciplina'=>$type]]]]];
$beforeFinancial=$db->rows('SELECT * FROM '.$db->table('lancamentos'));$key=keyP();$saved=$history->save($student,$body,$key);testP($history->save($student,$body,$key)===$saved,'histórico idempotente');testP($saved['escola_nome']==='ESCOLA ANTIGA'&&count($saved['anos'])===2&&count($saved['anos'][0]['disciplinas'])===2,'escola com vários anos e disciplinas');testP((int)$saved['codcoligada']===1&&$saved['anos'][0]['disciplinas'][0]['nota_final']==='APTO','coligada herdada e conceito preservado');
$update=$saved;$update['anos'][0]['disciplinas'][0]['nota_final']='9,5';$updated=$history->save($student,$update,keyP());testP($updated['anos'][0]['idano']===$saved['anos'][0]['idano']&&$updated['anos'][0]['disciplinas'][0]['idregistro_disciplina']===$saved['anos'][0]['disciplinas'][0]['idregistro_disciplina'],'edição preserva IDs de anos e disciplinas');deniedP(fn()=>$history->save($student,$saved,keyP()),'versão obsoleta bloqueada');
$bad=$updated;$bad['anos'][1]['disciplinas'][0]['idregistro_disciplina']=$updated['anos'][0]['disciplinas'][0]['idregistro_disciplina'];deniedP(fn()=>$history->save($student,$bad,keyP()),'disciplina de outro ano bloqueada');testP($history->listing($student)[0]===$updated,'falha desfaz alteração inteira');
$otherType=$history->typeSave(['nome'=>'Tipo outra coligada'],keyP());$bad=$updated;$bad['anos'][0]['disciplinas'][0]['idtipo_disciplina']=$otherType['idtipo_disciplina'];deniedP(fn()=>$history->save($student,$bad,keyP()),'tipo de outra coligada bloqueado');
$del=new EducacionalERP\Application\DeletionService($db,new EducacionalERP\Application\Operations($db));deniedP(fn()=>$del->remove('tipos_disciplina',$type,['versao'=>$types['versao'],'motivo'=>'TESTE'],keyP()),'tipo vinculado não pode ser excluído');
$inactive=EducacionalERP\Application\Coligadas::within(1,fn()=>$history->typeSave(array_merge($types,['ativo'=>0]),keyP()));$updated=$history->save($student,$updated,keyP());testP(count($updated['anos'])===2,'tipo inativo preservado em registros já vinculados');$bad=$body;deniedP(fn()=>$history->save($student,$bad,keyP()),'novo vínculo com tipo inativo bloqueado');
$trim=$updated;array_pop($trim['anos']);array_pop($trim['anos'][0]['disciplinas']);$trimmed=$history->save($student,$trim,keyP());testP(count($trimmed['anos'])===1&&count($trimmed['anos'][0]['disciplinas'])===1,'remoção de ano e disciplina reconciliada');
testP($beforeFinancial===$db->rows('SELECT * FROM '.$db->table('lancamentos')),'histórico não modifica financeiro');$out=(new EducacionalERP\Application\IntegrationService($db,new EducacionalERP\Application\Operations($db),$cat))->detail('alunos',$student);testP(isset($out['item']['historicos_anteriores']),'API do aluno inclui histórico anterior');
wp_set_current_user($rfUser);deniedP(fn()=>$history->save($student,$body,keyP()),'responsável não cadastra histórico');wp_set_current_user(1);$history->remove($student,(int)$trimmed['idhistorico'],['versao'=>$trimmed['versao']],keyP());testP($history->listing($student)===[],'exclusão completa auditada');
echo "PASS: histórico escolar anterior e tipos de disciplina\n";
