<?php
require __DIR__.'/sqlite-bootstrap.php';require dirname(__DIR__).'/autoload.php';
use EducacionalERP\Infrastructure\WordPress\{SchoolIdentity,Access};
use EducacionalERP\Domain\RuleViolation;
function sanitize_text_field($s){return trim(strip_tags($s));}function get_post_type($id){return $id===10?'attachment':'post';}function get_post_mime_type($id){return 'image/png';}function plugins_url($s,$f){return 'https://example.test/plugin/'.$s;}function admin_url($s){return 'https://example.test/wp-admin/'.$s;}function home_url($s){return 'https://example.test'.$s;}function add_query_arg($a,$b,$c=null){return $c?:$b;}define('EDERP_FILE',__FILE__);
Access::install();$n=0;function okS($b,$m){global $n;if(!$b)throw new RuntimeException($m);$n++;echo "PASS: $m\n";}function denyS($f,$m){try{$f();}catch(RuleViolation $e){okS(true,$m);return;}throw new RuntimeException($m);}
$d=SchoolIdentity::read();okS($d['nome']==='Colégio Journey','instalação existente preserva padrão inicial');$d['nome']='COLÉGIO NOVO';$d['email']='contato@example.test';$d['site']='https://example.test';$d['cnpj']='12.345.678/0001-90';$d['rua']='Rua Teste';$d['cor_primaria']='#8833dd';$d['logo_id']=10;$d['version']=SchoolIdentity::version();$result=SchoolIdentity::save($d);okS($result['data']['nome']==='COLÉGIO NOVO'&&SchoolIdentity::logo()==='https://test.example/foto.jpg','salva dados e logo da escola');okS(str_contains(SchoolIdentity::css(),'--j-action:#8833dd'),'cores geradas a partir da configuração');
denyS(fn()=>SchoolIdentity::save($d),'versão antiga não sobrescreve configuração');$d['version']=SchoolIdentity::version();
foreach(['cor_primaria'=>'red;}</style><script>','site'=>'javascript:alert(1)','email'=>'invalido','logo_id'=>99,'nome'=>''] as $key=>$value)denyS(fn()=>SchoolIdentity::save(array_merge($d,[$key=>$value])),'rejeita campo inválido '.$key);
$d['logo_id']=0;SchoolIdentity::save($d);okS(SchoolIdentity::logo()==='','remoção do logo não restaura Journey');$d['version']=SchoolIdentity::version();wp_set_current_user(wp_insert_user(['user_login'=>'secretaria.brand','role'=>'erp_secretaria']));denyS(fn()=>SchoolIdentity::save($d),'somente administrador altera identidade');denyS(fn()=>SchoolIdentity::payload(),'somente administrador consulta configuração completa');echo "$n verificações aprovadas\n";
