const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const code=fs.readFileSync(require('path').join(__dirname,'../assets/workflow.js'),'utf8');
const base={aluno:{idaluno:'1',codpessoa:'10',ra:'0001'},pessoa:{codpessoa:'10',nome:'Sofia Silva',data_nascimento:'2015-04-12'},responsaveis:[],matriculas:[],periodos_pendentes:[]};
const sleep=()=>new Promise(r=>setTimeout(r,15));
async function boot(screen,query='',data=base,admin=true){const calls=[],errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message)});
 const dom=new JSDOM(`<div class="ederp" data-erp-screen="${screen}"></div>`,{url:'https://example.test/wp-admin/admin.php?page=ederp-'+screen+query,runScripts:'dangerously',virtualConsole:vc});const w=dom.window;
 w.EDERP={root:'https://example.test/api/',admin:'https://example.test/wp-admin/admin.php',nonce:'test',caps:{people:true,academic:true,finance:true,changeGuardian:true,admin},parentescos:{pai:'Pai',mae:'Mãe',avo_feminina:'Avó',padrasto:'Padrasto',madrasta:'Madrasta'}};
 w.fetch=async(raw,opt={})=>{const u=new URL(raw),route=u.pathname.replace('/api/','');calls.push({route,url:u,options:opt,body:opt.body&&JSON.parse(opt.body)});let out;
 if(opt.method==='POST')out={id:'2',idaluno:'1',idvinculoperiodo:'5',idmatricula:'3'};
 else if(route==='turmas/9/plano')out={idplano:'4',versao:'1',nome:'Plano anual',valor_anuidade:'1200.00'};
 else if(route==='secretaria/alunos/1')out=data;
 else if(route==='secretaria/alunos')out={items:[{idaluno:'1',nome:'Sofia Silva',ra:'0001'}],total:1};
 else if(route.startsWith('opcoes/'))out={items:route.endsWith('pessoas')?[{id:'2',label:'Carlos Silva · CPF final 1234'}]:route.endsWith('turmas')?[{id:'9',label:'6º ano A · Ensino Fundamental · Matutino'}]:[{id:'7',label:'2027 — Ano letivo'}],more:false,page:1};
 else if(route.startsWith('cadastros/'))out={items:[],total:0};else out=[];
 return{ok:true,json:async()=>out};};
 w.eval(code);await sleep();await sleep();assert.deepEqual(errors,[]);return{dom,w,d:w.document,calls,errors};}
function click(d,text){const b=[...d.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);b.click();}
function choose(w,d,name,value){const s=d.querySelector(`select[name="${name}"]`);assert.ok(s,name);s.value=value;s.dispatchEvent(new w.Event('change'));return s;}
(async()=>{
 let x=await boot('alunos','&aluno=1&aba=responsaveis');choose(x.w,x.d,'codpessoa_responsavel','2');x.d.querySelector('input[name="responsavel_financeiro"]').checked=true;x.d.querySelector('form').requestSubmit();await sleep();let post=x.calls.find(c=>c.options.method==='POST');assert.equal(post.route,'alunos/1/responsaveis');assert.equal(post.body.parentesco,'pai');assert.equal(post.body.codpessoa_responsavel,'2');assert.equal(post.body.responsavel_financeiro,true);console.log('PASS: vínculo por nome envia pessoa e atribuições corretas');x.dom.window.close();
 x=await boot('matriculas','&aluno=1');choose(x.w,x.d,'codperiodo','7');x.d.querySelector('form').requestSubmit();await sleep();post=x.calls.find(c=>c.options.method==='POST');assert.equal(post.route,'alunos/1/periodos');assert.equal(post.body.codperiodo,'7');assert.ok(!x.d.querySelector('[name="idturma"]'));console.log('PASS: tela de período salva sem exigir turma ou financeiro');x.dom.window.close();
 x=await boot('matriculas','&aluno=1&vinculo=5',{...base,periodos_pendentes:[{idvinculoperiodo:'5',codperiodo:'7',codigo:'2027',descricao:'Ano letivo'}]});assert.equal(x.calls.find(c=>c.route==='opcoes/turmas').url.searchParams.get('codperiodo'),'7');choose(x.w,x.d,'idcurso','7');choose(x.w,x.d,'idturno','7');await sleep();choose(x.w,x.d,'idturma','9');await sleep();x.d.querySelector('[name=primeiro_vencimento]').value='2027-01-31';x.d.querySelector('form').requestSubmit();await sleep();post=x.calls.find(c=>c.options.method==='POST');assert.equal(post.route,'alunos/1/periodos/5/turma');assert.equal(post.body.idturma,'9');assert.ok(!x.d.querySelector('[name="valor_original_total"]'));assert.equal(post.body.quantidade_parcelas,'12');assert.equal(post.body.idplano,'4');console.log('PASS: turma filtrada e confirmação inclui plano e quantidade de parcelas');x.dom.window.close();
 x=await boot('alunos','&novo=1');choose(x.w,x.d,'codpessoa','2');x.d.querySelector('[name="ra"]').value='0003';x.d.querySelector('form').requestSubmit();await sleep();post=x.calls.find(c=>c.options.method==='POST');assert.deepEqual(post.body,{codpessoa:'2',ra:'0003',tipo_aluno:'REGULAR'});assert.equal(x.d.querySelector('[name="nome"]'),null);console.log('PASS: aluno nasce de pessoa já cadastrada');x.dom.window.close();
 x=await boot('alunos','&aluno=1',base,false);assert.equal(x.d.querySelector('form'),null);console.log('PASS: não administrador consulta ficha sem formulário de edição');x.dom.window.close();
 x=await boot('pessoas');const f=x.d.querySelector('form');assert.equal(f.querySelector('[name="data_nascimento"]').required,true);f.querySelector('[name="nome"]').value='João Silva';f.querySelector('[name="data_nascimento"]').value='1980-08-15';x.w.fetch=async()=>({ok:false,json:async()=>({code:'erp_username_required',message:'Escolha outro usuário'})});f.requestSubmit();await sleep();assert.equal(f.querySelector('[name="user_login"]').parentElement.hidden,false);assert.equal(f.querySelector('[name="user_login"]').required,true);assert.equal(f.querySelector('[name="nome"]').value,'João Silva');console.log('PASS: homônimo abre escolha de login sem perder cadastro');x.dom.window.close();
 x=await boot('academico');click(x.d,'Turmas');await sleep();assert.ok(x.d.querySelector('select[name="codperiodo"]'));assert.ok(x.d.querySelector('select[name="idcurso"]'));assert.ok(x.d.querySelector('select[name="idturno"]'));assert.equal(x.d.querySelector('input[name="codperiodo"]'),null);console.log('PASS: estrutura acadêmica usa seletores por nome');x.dom.window.close();
 x=await boot('alunos','&aluno=1');click(x.d,'Pais e responsáveis');await sleep();choose(x.w,x.d,'codpessoa_responsavel','2');x.d.querySelector('form').requestSubmit();await sleep();await sleep();assert.equal(x.d.querySelector('.erp-tabs .active').textContent,'Pais e responsáveis');console.log('PASS: salvar vínculo mantém a aba da família aberta');x.dom.window.close();
 x=await boot('rematriculas');choose(x.w,x.d,'codperiodo_destino','7');choose(x.w,x.d,'idcurso_origem','7');choose(x.w,x.d,'idcurso_destino','7');await sleep();choose(x.w,x.d,'idturma','9');click(x.d,'Adicionar turma à oferta');for(const [k,v]of Object.entries({data_abertura:'2027-01-01',data_encerramento:'2027-01-31',primeiro_vencimento:'2027-02-01',texto_termo:'Termo da oferta'}))x.d.querySelector('[name="'+k+'"]').value=v;x.d.querySelector('form').requestSubmit();await sleep();post=x.calls.find(c=>c.options.method==='POST');assert.equal(post.route,'ofertas-rematricula');assert.equal(post.body.valor_total,undefined);assert.deepEqual(post.body.turmas,['9']);console.log('PASS: oferta de rematrícula usa seletores sem impor valor ao plano da turma');x.dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
