<?php
declare(strict_types=1);
namespace EducacionalERP\Application;
use EducacionalERP\Domain\{Store,Input,RuleViolation,Money,CadastroText};
use EducacionalERP\Infrastructure\WordPress\{Access,Accounts};
final class Curriculum
{
    public const TABLES=['disciplinas'=>'iddisciplina','grades_curriculares'=>'idgrade','grade_disciplinas'=>'iditem','turma_grades'=>'idvinculo','professores'=>'idprofessor','professor_disciplinas'=>'idvinculo','professor_turmas'=>'idatribuicao','professor_valores_hora'=>'idvalor'];
    public function __construct(private Store $db){}
    private function owned(string $table,int $id,bool $lock=true):array{$r=$this->db->get($table,$id,$lock);if(isset($r['codcoligada'])&&(int)$r['codcoligada']!==Coligadas::current())throw new RuleViolation('Registro de outra coligada.');return $r;}
    public function listing():array
    {
        $out=[];foreach(array_keys(self::TABLES) as $t)$out[$t]=$this->db->rows('SELECT * FROM '.$this->db->table($t).' WHERE codcoligada=%d ORDER BY '.self::TABLES[$t],[Coligadas::current()]);
        foreach(['cursos','turmas','periodos_letivos','tipos_disciplina'] as $t)$out[$t]=$this->db->rows('SELECT * FROM '.$this->db->table($t).' WHERE codcoligada=%d',[Coligadas::current()]);
        foreach($out['professores'] as &$p)$p['nome']=$this->db->get('pessoas',(int)$p['codpessoa'])['nome'];unset($p);return $out;
    }
    private function amount(mixed $v):string {if(!is_scalar($v))throw new RuleViolation('Valor inválido.');$c=Money::cents((string)$v);if($c<0||$c>999999999999)throw new RuleViolation('Valor fora do limite.');return Money::format($c);}
    private function capable(int $prof,int $disc):void{$p=$this->owned('professores',$prof);$d=$this->owned('disciplinas',$disc);if(!(int)$p['ativo']||!(int)$d['ativo'])throw new RuleViolation('Professor ou disciplina inativo.');if(!$this->db->row('SELECT idvinculo FROM '.$this->db->table('professor_disciplinas').' WHERE idprofessor=%d AND iddisciplina=%d FOR UPDATE',[$prof,$disc]))throw new RuleViolation('Vincule a disciplina ao professor primeiro.');}
    public function save(string $table,array $d,string $key):array
    {
        Access::requireAdmin();if(!isset(self::TABLES[$table]))throw new RuleViolation('Cadastro inválido.');return $this->db->atomic(fn()=>(new Operations($this->db))->run($key,'curriculo_'.$table,$d,function()use($table,$d,$key){
            $pk=self::TABLES[$table];$id=empty($d[$pk])?null:Input::id($d[$pk]);$before=$id?$this->owned($table,$id):null;if($before&&(string)($d['versao']??'')!==(string)$before['versao'])throw new RuleViolation('Cadastro alterado. Reabra o modal.');$r=[];
            switch($table){
                case 'disciplinas':$type=$this->owned('tipos_disciplina',Input::id($d['idtipo_disciplina']??null));if(!(int)$type['ativo'])throw new RuleViolation('Tipo de disciplina inativo.');$r=['codigo'=>CadastroText::upper(Input::text($d['codigo']??null,30)),'nome'=>CadastroText::upper(Input::text($d['nome']??null,120)),'idtipo_disciplina'=>$type['idtipo_disciplina']];break;
                case 'grades_curriculares':$course=$this->owned('cursos',Input::id($d['idcurso']??null));if(!(int)$course['ativo'])throw new RuleViolation('Curso inativo.');if($before&&(int)$before['idcurso']!==(int)$course['idcurso']&&$this->db->row('SELECT idvinculo FROM '.$this->db->table('turma_grades').' WHERE idgrade=%d',[$id]))throw new RuleViolation('Grade em uso não pode mudar de curso.');$r=['codigo'=>CadastroText::upper(Input::text($d['codigo']??null,30)),'nome'=>CadastroText::upper(Input::text($d['nome']??null,120)),'idcurso'=>$course['idcurso']];break;
                case 'professores':$person=$this->db->get('pessoas',Input::id($d['codpessoa']??null),true);if(!(int)$person['ativo'])throw new RuleViolation('Pessoa inativa.');if($before&&(int)$before['codpessoa']!==(int)$person['codpessoa'])throw new RuleViolation('A pessoa do professor não pode ser substituída.');$r=['codpessoa'=>$person['codpessoa']];break;
                case 'grade_disciplinas':$grade=$this->owned('grades_curriculares',Input::id($d['idgrade']??null));$disc=$this->owned('disciplinas',Input::id($d['iddisciplina']??null));if(!(int)$grade['ativo']||!(int)$disc['ativo'])throw new RuleViolation('Grade ou disciplina inativa.');$r=['idgrade'=>$grade['idgrade'],'iddisciplina'=>$disc['iddisciplina'],'carga_horaria'=>$this->amount($d['carga_horaria']??'0'),'ordem'=>max(0,min(9999,(int)($d['ordem']??0)))];break;
                case 'turma_grades':$class=$this->owned('turmas',Input::id($d['idturma']??null));$grade=$this->owned('grades_curriculares',Input::id($d['idgrade']??null));if(!(int)$grade['ativo']||(int)$grade['idcurso']!==(int)$class['idcurso'])throw new RuleViolation('A grade deve estar ativa e pertencer ao curso da turma.');foreach($this->db->rows('SELECT iddisciplina FROM '.$this->db->table('professor_turmas').' WHERE idturma=%d',[(int)$class['idturma']]) as $link)if(!$this->db->row('SELECT iditem FROM '.$this->db->table('grade_disciplinas').' WHERE idgrade=%d AND iddisciplina=%d',[(int)$grade['idgrade'],(int)$link['iddisciplina']]))throw new RuleViolation('A nova grade não contém uma disciplina com professor já atribuído.');$r=['idturma'=>$class['idturma'],'idgrade'=>$grade['idgrade']];break;
                case 'professor_disciplinas':$prof=$this->owned('professores',Input::id($d['idprofessor']??null));$disc=$this->owned('disciplinas',Input::id($d['iddisciplina']??null));$r=['idprofessor'=>$prof['idprofessor'],'iddisciplina'=>$disc['iddisciplina']];break;
                case 'professor_valores_hora':case 'professor_turmas':$prof=Input::id($d['idprofessor']??null);$disc=Input::id($d['iddisciplina']??null);$period=$this->owned('periodos_letivos',Input::id($d['codperiodo']??null));$this->capable($prof,$disc);$r=['idprofessor'=>$prof,'iddisciplina'=>$disc,'codperiodo'=>$period['codperiodo']];if($table==='professor_valores_hora')$r['valor_hora']=$this->amount($d['valor_hora']??null);else{$class=$this->owned('turmas',Input::id($d['idturma']??null));if((int)$class['codperiodo']!==(int)$period['codperiodo'])throw new RuleViolation('Turma de outro período.');$grade=$this->db->row('SELECT idgrade FROM '.$this->db->table('turma_grades').' WHERE idturma=%d FOR UPDATE',[(int)$class['idturma']]);if(!$grade||!$this->db->row('SELECT iditem FROM '.$this->db->table('grade_disciplinas').' WHERE idgrade=%d AND iddisciplina=%d FOR UPDATE',[(int)$grade['idgrade'],$disc]))throw new RuleViolation('Disciplina ausente na grade da turma.');$r['idturma']=$class['idturma'];}break;
            }
            if(in_array($table,['disciplinas','grades_curriculares','professores'],true)){if(isset($d['ativo'])&&!in_array($d['ativo'],[0,1,'0','1',false,true],true))throw new RuleViolation('Situação inválida.');$r['ativo']=(int)($d['ativo']??1);}
            // Reference identity remains immutable; remove unused links and create new ones.
            if($before&&!in_array($table,['disciplinas','grades_curriculares','professores','turma_grades'],true))foreach($r as $f=>$v)if(str_starts_with($f,'id')||$f==='codperiodo')if((string)$before[$f] !== (string)$v)throw new RuleViolation('Edite apenas os valores deste vínculo. Para mudar referências, exclua o vínculo sem dependências e crie outro.');
            if($before&&$table==='turma_grades'&&(int)$before['idturma']!==(int)$r['idturma'])throw new RuleViolation('A turma do vínculo não pode mudar.');
            if($id)$this->db->update($table,$id,$r);else $id=$this->db->insert($table,$r);if($table==='professores')(new Accounts($this->db))->sync((int)$r['codpessoa']);$after=$this->db->get($table,$id);$this->db->audit($table,$id,$before?'editar':'criar',$before,$after,$key);return $after;
        }));
    }
    public function remove(string $table,int $id,array $d,string $key):array
    {
        Access::requireAdmin();if(!isset(self::TABLES[$table]))throw new RuleViolation('Cadastro inválido.');return $this->db->atomic(function()use($table,$id,$d,$key){$before=$this->owned($table,$id);if((string)($d['versao']??'')!==(string)$before['versao'])throw new RuleViolation('Cadastro alterado.');$dependencies=['disciplinas'=>['grade_disciplinas'=>'iddisciplina','professor_disciplinas'=>'iddisciplina','professor_turmas'=>'iddisciplina','professor_valores_hora'=>'iddisciplina'],'grades_curriculares'=>['grade_disciplinas'=>'idgrade','turma_grades'=>'idgrade'],'professores'=>['professor_disciplinas'=>'idprofessor','professor_turmas'=>'idprofessor','professor_valores_hora'=>'idprofessor']];foreach($dependencies[$table]??[] as $t=>$f)if($this->db->row('SELECT * FROM '.$this->db->table($t)." WHERE $f=%d FOR UPDATE",[$id]))throw new RuleViolation('Existem vínculos dependentes. Remova-os antes de excluir.');
            if($table==='professor_disciplinas')foreach(['professor_turmas','professor_valores_hora'] as $t)if($this->db->row('SELECT * FROM '.$this->db->table($t).' WHERE idprofessor=%d AND iddisciplina=%d FOR UPDATE',[(int)$before['idprofessor'],(int)$before['iddisciplina']]))throw new RuleViolation('Disciplina do professor possui turmas ou valores por período.');
            if($table==='turma_grades'&&$this->db->row('SELECT * FROM '.$this->db->table('professor_turmas').' WHERE idturma=%d FOR UPDATE',[(int)$before['idturma']]))throw new RuleViolation('A turma possui professores atribuídos.');
            if($table==='grade_disciplinas'&&$this->db->row('SELECT p.idatribuicao FROM '.$this->db->table('professor_turmas').' p JOIN '.$this->db->table('turma_grades').' g ON g.idturma=p.idturma WHERE g.idgrade=%d AND p.iddisciplina=%d FOR UPDATE',[(int)$before['idgrade'],(int)$before['iddisciplina']]))throw new RuleViolation('Disciplina possui professores nas turmas da grade.');
            $this->db->query('DELETE FROM '.$this->db->table($table).' WHERE '.self::TABLES[$table].'=%d',[$id]);if($table==='professores')(new Accounts($this->db))->sync((int)$before['codpessoa']);$this->db->audit($table,$id,'excluir',$before,[],$key);return ['excluido'=>true];});
    }
}
